// macro.h
// Preprocessor utils
// Version 1.0.2
// Autogenerated, don't touch.

#pragma once

#define MA_STR(...) MA_STR_impl(__VA_ARGS__)
#define MA_STR_impl(...) #__VA_ARGS__

#define MA_CAT(x,y) MA_CAT_impl(x,y)
#define MA_CAT_impl(x,y) x##y

#define MA_NULL(...)
#define MA_IDENTITY(...) __VA_ARGS__

#define MA_COMMA() ,
#define MA_SEMICOLON() ;
#define MA_PLUS() +

#define MA_OVERLOAD(name, ...) MA_CAT(name, MA_VA_SIZE(__VA_ARGS__))(__VA_ARGS__)

#define MA_CALL(macro, ...) macro(__VA_ARGS__)
#define MA_CALL_A(macro, ...) macro(__VA_ARGS__)
#define MA_IMPL_CALL(macro, ...) macro(__VA_ARGS__) // For implementation use
#define MA_IMPL_CALL_A(macro, ...) macro(__VA_ARGS__) // For implementation use

#define MA_VA_FIRST(...) MA_VA_FIRST_impl(__VA_ARGS__,)
#define MA_VA_FIRST_impl(x, ...) x

#define MA_VA_NO_FIRST(x, ...) __VA_ARGS__

#define MA_SEQ_FIRST(seq) MA_SEQ_FIRST_impl seq )
#define MA_SEQ_FIRST_impl(...) __VA_ARGS__ MA_NULL(

#define MA_SEQ_NO_FIRST(seq) MA_NULL seq

#define MA_VA_SIZE(...) MA_VA_SIZE_impl(__VA_ARGS__,65,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)
#define MA_VA_SIZE_impl(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,p60,p61,p62,p63,p64,p65,size,...) size

#define MA_SEQ_SIZE(seq) MA_CAT(MA_SEQ_SIZE_impl_0 seq, _val)
#define MA_SEQ_SIZE_impl_0(...) MA_SEQ_SIZE_impl_1
#define MA_SEQ_SIZE_impl_1(...) MA_SEQ_SIZE_impl_2
#define MA_SEQ_SIZE_impl_2(...) MA_SEQ_SIZE_impl_3
#define MA_SEQ_SIZE_impl_3(...) MA_SEQ_SIZE_impl_4
#define MA_SEQ_SIZE_impl_4(...) MA_SEQ_SIZE_impl_5
#define MA_SEQ_SIZE_impl_5(...) MA_SEQ_SIZE_impl_6
#define MA_SEQ_SIZE_impl_6(...) MA_SEQ_SIZE_impl_7
#define MA_SEQ_SIZE_impl_7(...) MA_SEQ_SIZE_impl_8
#define MA_SEQ_SIZE_impl_8(...) MA_SEQ_SIZE_impl_9
#define MA_SEQ_SIZE_impl_9(...) MA_SEQ_SIZE_impl_10
#define MA_SEQ_SIZE_impl_10(...) MA_SEQ_SIZE_impl_11
#define MA_SEQ_SIZE_impl_11(...) MA_SEQ_SIZE_impl_12
#define MA_SEQ_SIZE_impl_12(...) MA_SEQ_SIZE_impl_13
#define MA_SEQ_SIZE_impl_13(...) MA_SEQ_SIZE_impl_14
#define MA_SEQ_SIZE_impl_14(...) MA_SEQ_SIZE_impl_15
#define MA_SEQ_SIZE_impl_15(...) MA_SEQ_SIZE_impl_16
#define MA_SEQ_SIZE_impl_16(...) MA_SEQ_SIZE_impl_17
#define MA_SEQ_SIZE_impl_17(...) MA_SEQ_SIZE_impl_18
#define MA_SEQ_SIZE_impl_18(...) MA_SEQ_SIZE_impl_19
#define MA_SEQ_SIZE_impl_19(...) MA_SEQ_SIZE_impl_20
#define MA_SEQ_SIZE_impl_20(...) MA_SEQ_SIZE_impl_21
#define MA_SEQ_SIZE_impl_21(...) MA_SEQ_SIZE_impl_22
#define MA_SEQ_SIZE_impl_22(...) MA_SEQ_SIZE_impl_23
#define MA_SEQ_SIZE_impl_23(...) MA_SEQ_SIZE_impl_24
#define MA_SEQ_SIZE_impl_24(...) MA_SEQ_SIZE_impl_25
#define MA_SEQ_SIZE_impl_25(...) MA_SEQ_SIZE_impl_26
#define MA_SEQ_SIZE_impl_26(...) MA_SEQ_SIZE_impl_27
#define MA_SEQ_SIZE_impl_27(...) MA_SEQ_SIZE_impl_28
#define MA_SEQ_SIZE_impl_28(...) MA_SEQ_SIZE_impl_29
#define MA_SEQ_SIZE_impl_29(...) MA_SEQ_SIZE_impl_30
#define MA_SEQ_SIZE_impl_30(...) MA_SEQ_SIZE_impl_31
#define MA_SEQ_SIZE_impl_31(...) MA_SEQ_SIZE_impl_32
#define MA_SEQ_SIZE_impl_32(...) MA_SEQ_SIZE_impl_33
#define MA_SEQ_SIZE_impl_33(...) MA_SEQ_SIZE_impl_34
#define MA_SEQ_SIZE_impl_34(...) MA_SEQ_SIZE_impl_35
#define MA_SEQ_SIZE_impl_35(...) MA_SEQ_SIZE_impl_36
#define MA_SEQ_SIZE_impl_36(...) MA_SEQ_SIZE_impl_37
#define MA_SEQ_SIZE_impl_37(...) MA_SEQ_SIZE_impl_38
#define MA_SEQ_SIZE_impl_38(...) MA_SEQ_SIZE_impl_39
#define MA_SEQ_SIZE_impl_39(...) MA_SEQ_SIZE_impl_40
#define MA_SEQ_SIZE_impl_40(...) MA_SEQ_SIZE_impl_41
#define MA_SEQ_SIZE_impl_41(...) MA_SEQ_SIZE_impl_42
#define MA_SEQ_SIZE_impl_42(...) MA_SEQ_SIZE_impl_43
#define MA_SEQ_SIZE_impl_43(...) MA_SEQ_SIZE_impl_44
#define MA_SEQ_SIZE_impl_44(...) MA_SEQ_SIZE_impl_45
#define MA_SEQ_SIZE_impl_45(...) MA_SEQ_SIZE_impl_46
#define MA_SEQ_SIZE_impl_46(...) MA_SEQ_SIZE_impl_47
#define MA_SEQ_SIZE_impl_47(...) MA_SEQ_SIZE_impl_48
#define MA_SEQ_SIZE_impl_48(...) MA_SEQ_SIZE_impl_49
#define MA_SEQ_SIZE_impl_49(...) MA_SEQ_SIZE_impl_50
#define MA_SEQ_SIZE_impl_50(...) MA_SEQ_SIZE_impl_51
#define MA_SEQ_SIZE_impl_51(...) MA_SEQ_SIZE_impl_52
#define MA_SEQ_SIZE_impl_52(...) MA_SEQ_SIZE_impl_53
#define MA_SEQ_SIZE_impl_53(...) MA_SEQ_SIZE_impl_54
#define MA_SEQ_SIZE_impl_54(...) MA_SEQ_SIZE_impl_55
#define MA_SEQ_SIZE_impl_55(...) MA_SEQ_SIZE_impl_56
#define MA_SEQ_SIZE_impl_56(...) MA_SEQ_SIZE_impl_57
#define MA_SEQ_SIZE_impl_57(...) MA_SEQ_SIZE_impl_58
#define MA_SEQ_SIZE_impl_58(...) MA_SEQ_SIZE_impl_59
#define MA_SEQ_SIZE_impl_59(...) MA_SEQ_SIZE_impl_60
#define MA_SEQ_SIZE_impl_60(...) MA_SEQ_SIZE_impl_61
#define MA_SEQ_SIZE_impl_61(...) MA_SEQ_SIZE_impl_62
#define MA_SEQ_SIZE_impl_62(...) MA_SEQ_SIZE_impl_63
#define MA_SEQ_SIZE_impl_63(...) MA_SEQ_SIZE_impl_64
#define MA_SEQ_SIZE_impl_64(...) MA_SEQ_SIZE_impl_65
#define MA_SEQ_SIZE_impl_0_val 0
#define MA_SEQ_SIZE_impl_1_val 1
#define MA_SEQ_SIZE_impl_2_val 2
#define MA_SEQ_SIZE_impl_3_val 3
#define MA_SEQ_SIZE_impl_4_val 4
#define MA_SEQ_SIZE_impl_5_val 5
#define MA_SEQ_SIZE_impl_6_val 6
#define MA_SEQ_SIZE_impl_7_val 7
#define MA_SEQ_SIZE_impl_8_val 8
#define MA_SEQ_SIZE_impl_9_val 9
#define MA_SEQ_SIZE_impl_10_val 10
#define MA_SEQ_SIZE_impl_11_val 11
#define MA_SEQ_SIZE_impl_12_val 12
#define MA_SEQ_SIZE_impl_13_val 13
#define MA_SEQ_SIZE_impl_14_val 14
#define MA_SEQ_SIZE_impl_15_val 15
#define MA_SEQ_SIZE_impl_16_val 16
#define MA_SEQ_SIZE_impl_17_val 17
#define MA_SEQ_SIZE_impl_18_val 18
#define MA_SEQ_SIZE_impl_19_val 19
#define MA_SEQ_SIZE_impl_20_val 20
#define MA_SEQ_SIZE_impl_21_val 21
#define MA_SEQ_SIZE_impl_22_val 22
#define MA_SEQ_SIZE_impl_23_val 23
#define MA_SEQ_SIZE_impl_24_val 24
#define MA_SEQ_SIZE_impl_25_val 25
#define MA_SEQ_SIZE_impl_26_val 26
#define MA_SEQ_SIZE_impl_27_val 27
#define MA_SEQ_SIZE_impl_28_val 28
#define MA_SEQ_SIZE_impl_29_val 29
#define MA_SEQ_SIZE_impl_30_val 30
#define MA_SEQ_SIZE_impl_31_val 31
#define MA_SEQ_SIZE_impl_32_val 32
#define MA_SEQ_SIZE_impl_33_val 33
#define MA_SEQ_SIZE_impl_34_val 34
#define MA_SEQ_SIZE_impl_35_val 35
#define MA_SEQ_SIZE_impl_36_val 36
#define MA_SEQ_SIZE_impl_37_val 37
#define MA_SEQ_SIZE_impl_38_val 38
#define MA_SEQ_SIZE_impl_39_val 39
#define MA_SEQ_SIZE_impl_40_val 40
#define MA_SEQ_SIZE_impl_41_val 41
#define MA_SEQ_SIZE_impl_42_val 42
#define MA_SEQ_SIZE_impl_43_val 43
#define MA_SEQ_SIZE_impl_44_val 44
#define MA_SEQ_SIZE_impl_45_val 45
#define MA_SEQ_SIZE_impl_46_val 46
#define MA_SEQ_SIZE_impl_47_val 47
#define MA_SEQ_SIZE_impl_48_val 48
#define MA_SEQ_SIZE_impl_49_val 49
#define MA_SEQ_SIZE_impl_50_val 50
#define MA_SEQ_SIZE_impl_51_val 51
#define MA_SEQ_SIZE_impl_52_val 52
#define MA_SEQ_SIZE_impl_53_val 53
#define MA_SEQ_SIZE_impl_54_val 54
#define MA_SEQ_SIZE_impl_55_val 55
#define MA_SEQ_SIZE_impl_56_val 56
#define MA_SEQ_SIZE_impl_57_val 57
#define MA_SEQ_SIZE_impl_58_val 58
#define MA_SEQ_SIZE_impl_59_val 59
#define MA_SEQ_SIZE_impl_60_val 60
#define MA_SEQ_SIZE_impl_61_val 61
#define MA_SEQ_SIZE_impl_62_val 62
#define MA_SEQ_SIZE_impl_63_val 63
#define MA_SEQ_SIZE_impl_64_val 64

#define MA_VA_TO_SEQ(...) MA_CAT(MA_VA_TO_SEQ_impl_, MA_VA_SIZE(__VA_ARGS__,))(__VA_ARGS__,)
#define MA_VA_TO_SEQ_TRAILING_COMMA(...) MA_CAT(MA_VA_TO_SEQ_impl_, MA_VA_SIZE(__VA_ARGS__))(__VA_ARGS__)
#define MA_VA_TO_SEQ_impl_null
#define MA_VA_TO_SEQ_impl_1(empty) MA_VA_TO_SEQ_impl_null##empty // If you get a error message pointing to this line, you forgot a trailing comma somewhere.
#define MA_VA_TO_SEQ_impl_2(p1,empty) (p1) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_3(p1,p2,empty) (p1)(p2) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_4(p1,p2,p3,empty) (p1)(p2)(p3) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_5(p1,p2,p3,p4,empty) (p1)(p2)(p3)(p4) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_6(p1,p2,p3,p4,p5,empty) (p1)(p2)(p3)(p4)(p5) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_7(p1,p2,p3,p4,p5,p6,empty) (p1)(p2)(p3)(p4)(p5)(p6) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_8(p1,p2,p3,p4,p5,p6,p7,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_9(p1,p2,p3,p4,p5,p6,p7,p8,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_10(p1,p2,p3,p4,p5,p6,p7,p8,p9,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_11(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_12(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_13(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_14(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_15(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_16(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_17(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_18(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_19(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_20(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_21(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_22(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_23(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_24(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_25(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_26(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_27(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_28(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_29(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_30(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_31(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_32(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_33(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_34(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_35(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_36(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_37(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_38(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_39(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_40(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_41(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_42(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_43(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_44(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_45(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_46(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_47(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_48(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_49(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_50(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_51(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_52(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_53(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_54(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_55(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_56(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_57(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_58(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_59(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_60(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58)(p59) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_61(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,p60,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58)(p59)(p60) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_62(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,p60,p61,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58)(p59)(p60)(p61) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_63(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,p60,p61,p62,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58)(p59)(p60)(p61)(p62) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_64(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,p60,p61,p62,p63,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58)(p59)(p60)(p61)(p62)(p63) MA_VA_TO_SEQ_impl_1(empty)
#define MA_VA_TO_SEQ_impl_65(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,p17,p18,p19,p20,p21,p22,p23,p24,p25,p26,p27,p28,p29,p30,p31,p32,p33,p34,p35,p36,p37,p38,p39,p40,p41,p42,p43,p44,p45,p46,p47,p48,p49,p50,p51,p52,p53,p54,p55,p56,p57,p58,p59,p60,p61,p62,p63,p64,empty) (p1)(p2)(p3)(p4)(p5)(p6)(p7)(p8)(p9)(p10)(p11)(p12)(p13)(p14)(p15)(p16)(p17)(p18)(p19)(p20)(p21)(p22)(p23)(p24)(p25)(p26)(p27)(p28)(p29)(p30)(p31)(p32)(p33)(p34)(p35)(p36)(p37)(p38)(p39)(p40)(p41)(p42)(p43)(p44)(p45)(p46)(p47)(p48)(p49)(p50)(p51)(p52)(p53)(p54)(p55)(p56)(p57)(p58)(p59)(p60)(p61)(p62)(p63)(p64) MA_VA_TO_SEQ_impl_1(empty)

#define MA_SEQ_TO_VA(seq) MA_CAT(MA_SEQ_TO_VA_impl_, MA_SEQ_SIZE(seq)) seq
#define MA_SEQ_TO_VA_impl_0
#define MA_SEQ_TO_VA_impl_1(...) __VA_ARGS__
#define MA_SEQ_TO_VA_impl_2(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_1
#define MA_SEQ_TO_VA_impl_3(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_2
#define MA_SEQ_TO_VA_impl_4(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_3
#define MA_SEQ_TO_VA_impl_5(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_4
#define MA_SEQ_TO_VA_impl_6(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_5
#define MA_SEQ_TO_VA_impl_7(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_6
#define MA_SEQ_TO_VA_impl_8(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_7
#define MA_SEQ_TO_VA_impl_9(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_8
#define MA_SEQ_TO_VA_impl_10(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_9
#define MA_SEQ_TO_VA_impl_11(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_10
#define MA_SEQ_TO_VA_impl_12(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_11
#define MA_SEQ_TO_VA_impl_13(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_12
#define MA_SEQ_TO_VA_impl_14(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_13
#define MA_SEQ_TO_VA_impl_15(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_14
#define MA_SEQ_TO_VA_impl_16(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_15
#define MA_SEQ_TO_VA_impl_17(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_16
#define MA_SEQ_TO_VA_impl_18(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_17
#define MA_SEQ_TO_VA_impl_19(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_18
#define MA_SEQ_TO_VA_impl_20(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_19
#define MA_SEQ_TO_VA_impl_21(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_20
#define MA_SEQ_TO_VA_impl_22(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_21
#define MA_SEQ_TO_VA_impl_23(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_22
#define MA_SEQ_TO_VA_impl_24(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_23
#define MA_SEQ_TO_VA_impl_25(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_24
#define MA_SEQ_TO_VA_impl_26(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_25
#define MA_SEQ_TO_VA_impl_27(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_26
#define MA_SEQ_TO_VA_impl_28(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_27
#define MA_SEQ_TO_VA_impl_29(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_28
#define MA_SEQ_TO_VA_impl_30(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_29
#define MA_SEQ_TO_VA_impl_31(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_30
#define MA_SEQ_TO_VA_impl_32(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_31
#define MA_SEQ_TO_VA_impl_33(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_32
#define MA_SEQ_TO_VA_impl_34(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_33
#define MA_SEQ_TO_VA_impl_35(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_34
#define MA_SEQ_TO_VA_impl_36(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_35
#define MA_SEQ_TO_VA_impl_37(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_36
#define MA_SEQ_TO_VA_impl_38(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_37
#define MA_SEQ_TO_VA_impl_39(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_38
#define MA_SEQ_TO_VA_impl_40(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_39
#define MA_SEQ_TO_VA_impl_41(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_40
#define MA_SEQ_TO_VA_impl_42(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_41
#define MA_SEQ_TO_VA_impl_43(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_42
#define MA_SEQ_TO_VA_impl_44(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_43
#define MA_SEQ_TO_VA_impl_45(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_44
#define MA_SEQ_TO_VA_impl_46(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_45
#define MA_SEQ_TO_VA_impl_47(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_46
#define MA_SEQ_TO_VA_impl_48(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_47
#define MA_SEQ_TO_VA_impl_49(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_48
#define MA_SEQ_TO_VA_impl_50(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_49
#define MA_SEQ_TO_VA_impl_51(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_50
#define MA_SEQ_TO_VA_impl_52(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_51
#define MA_SEQ_TO_VA_impl_53(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_52
#define MA_SEQ_TO_VA_impl_54(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_53
#define MA_SEQ_TO_VA_impl_55(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_54
#define MA_SEQ_TO_VA_impl_56(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_55
#define MA_SEQ_TO_VA_impl_57(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_56
#define MA_SEQ_TO_VA_impl_58(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_57
#define MA_SEQ_TO_VA_impl_59(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_58
#define MA_SEQ_TO_VA_impl_60(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_59
#define MA_SEQ_TO_VA_impl_61(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_60
#define MA_SEQ_TO_VA_impl_62(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_61
#define MA_SEQ_TO_VA_impl_63(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_62
#define MA_SEQ_TO_VA_impl_64(...) __VA_ARGS__,MA_SEQ_TO_VA_impl_63

#define MA_SEQ_TO_VA_PARENS(seq) MA_CAT(MA_SEQ_TO_VA_PARENS_impl_, MA_SEQ_SIZE(seq)) seq
#define MA_SEQ_TO_VA_PARENS_impl_0
#define MA_SEQ_TO_VA_PARENS_impl_1(...) (__VA_ARGS__)
#define MA_SEQ_TO_VA_PARENS_impl_2(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_1
#define MA_SEQ_TO_VA_PARENS_impl_3(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_2
#define MA_SEQ_TO_VA_PARENS_impl_4(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_3
#define MA_SEQ_TO_VA_PARENS_impl_5(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_4
#define MA_SEQ_TO_VA_PARENS_impl_6(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_5
#define MA_SEQ_TO_VA_PARENS_impl_7(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_6
#define MA_SEQ_TO_VA_PARENS_impl_8(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_7
#define MA_SEQ_TO_VA_PARENS_impl_9(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_8
#define MA_SEQ_TO_VA_PARENS_impl_10(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_9
#define MA_SEQ_TO_VA_PARENS_impl_11(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_10
#define MA_SEQ_TO_VA_PARENS_impl_12(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_11
#define MA_SEQ_TO_VA_PARENS_impl_13(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_12
#define MA_SEQ_TO_VA_PARENS_impl_14(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_13
#define MA_SEQ_TO_VA_PARENS_impl_15(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_14
#define MA_SEQ_TO_VA_PARENS_impl_16(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_15
#define MA_SEQ_TO_VA_PARENS_impl_17(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_16
#define MA_SEQ_TO_VA_PARENS_impl_18(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_17
#define MA_SEQ_TO_VA_PARENS_impl_19(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_18
#define MA_SEQ_TO_VA_PARENS_impl_20(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_19
#define MA_SEQ_TO_VA_PARENS_impl_21(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_20
#define MA_SEQ_TO_VA_PARENS_impl_22(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_21
#define MA_SEQ_TO_VA_PARENS_impl_23(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_22
#define MA_SEQ_TO_VA_PARENS_impl_24(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_23
#define MA_SEQ_TO_VA_PARENS_impl_25(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_24
#define MA_SEQ_TO_VA_PARENS_impl_26(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_25
#define MA_SEQ_TO_VA_PARENS_impl_27(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_26
#define MA_SEQ_TO_VA_PARENS_impl_28(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_27
#define MA_SEQ_TO_VA_PARENS_impl_29(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_28
#define MA_SEQ_TO_VA_PARENS_impl_30(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_29
#define MA_SEQ_TO_VA_PARENS_impl_31(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_30
#define MA_SEQ_TO_VA_PARENS_impl_32(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_31
#define MA_SEQ_TO_VA_PARENS_impl_33(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_32
#define MA_SEQ_TO_VA_PARENS_impl_34(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_33
#define MA_SEQ_TO_VA_PARENS_impl_35(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_34
#define MA_SEQ_TO_VA_PARENS_impl_36(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_35
#define MA_SEQ_TO_VA_PARENS_impl_37(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_36
#define MA_SEQ_TO_VA_PARENS_impl_38(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_37
#define MA_SEQ_TO_VA_PARENS_impl_39(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_38
#define MA_SEQ_TO_VA_PARENS_impl_40(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_39
#define MA_SEQ_TO_VA_PARENS_impl_41(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_40
#define MA_SEQ_TO_VA_PARENS_impl_42(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_41
#define MA_SEQ_TO_VA_PARENS_impl_43(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_42
#define MA_SEQ_TO_VA_PARENS_impl_44(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_43
#define MA_SEQ_TO_VA_PARENS_impl_45(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_44
#define MA_SEQ_TO_VA_PARENS_impl_46(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_45
#define MA_SEQ_TO_VA_PARENS_impl_47(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_46
#define MA_SEQ_TO_VA_PARENS_impl_48(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_47
#define MA_SEQ_TO_VA_PARENS_impl_49(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_48
#define MA_SEQ_TO_VA_PARENS_impl_50(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_49
#define MA_SEQ_TO_VA_PARENS_impl_51(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_50
#define MA_SEQ_TO_VA_PARENS_impl_52(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_51
#define MA_SEQ_TO_VA_PARENS_impl_53(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_52
#define MA_SEQ_TO_VA_PARENS_impl_54(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_53
#define MA_SEQ_TO_VA_PARENS_impl_55(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_54
#define MA_SEQ_TO_VA_PARENS_impl_56(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_55
#define MA_SEQ_TO_VA_PARENS_impl_57(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_56
#define MA_SEQ_TO_VA_PARENS_impl_58(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_57
#define MA_SEQ_TO_VA_PARENS_impl_59(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_58
#define MA_SEQ_TO_VA_PARENS_impl_60(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_59
#define MA_SEQ_TO_VA_PARENS_impl_61(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_60
#define MA_SEQ_TO_VA_PARENS_impl_62(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_61
#define MA_SEQ_TO_VA_PARENS_impl_63(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_62
#define MA_SEQ_TO_VA_PARENS_impl_64(...) (__VA_ARGS__),MA_SEQ_TO_VA_PARENS_impl_63

// In MA_*_FOR_EACH below, `macro` argument is called as `macro(i, data, element)`. Note that to simplify implementation, `i` counts backwards from N-1 to 0.

#define MA_VA_FOR_EACH(macro, sep, data, ...) MA_SEQ_FOR_EACH(macro, sep, data, MA_VA_TO_SEQ(__VA_ARGS__))
#define MA_VA_FOR_EACH_TRAILING_COMMA(macro, sep, data, ...) MA_SEQ_FOR_EACH(macro, sep, data, MA_VA_TO_SEQ_TRAILING_COMMA(__VA_ARGS__))
#define MA_VA_FOR_EACH_A(macro, sep, data, ...) MA_SEQ_FOR_EACH_A(macro, sep, data, MA_VA_TO_SEQ(__VA_ARGS__))
#define MA_VA_FOR_EACH_A_TRAILING_COMMA(macro, sep, data, ...) MA_SEQ_FOR_EACH_A(macro, sep, data, MA_VA_TO_SEQ_TRAILING_COMMA(__VA_ARGS__))

#define MA_SEQ_FOR_EACH(macro, sep, data, seq) MA_CAT(MA_SEQ_FOR_EACH_impl_, MA_SEQ_SIZE(seq))(macro, sep, data, seq)
#define MA_SEQ_FOR_EACH_impl_0(macro, sep, data, seq)
#define MA_SEQ_FOR_EACH_impl_1(macro, sep, data, seq) MA_IMPL_CALL(macro, 0, data, MA_SEQ_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_2(macro, sep, data, seq) MA_IMPL_CALL(macro, 1, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_1(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_3(macro, sep, data, seq) MA_IMPL_CALL(macro, 2, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_2(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_4(macro, sep, data, seq) MA_IMPL_CALL(macro, 3, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_3(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_5(macro, sep, data, seq) MA_IMPL_CALL(macro, 4, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_4(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_6(macro, sep, data, seq) MA_IMPL_CALL(macro, 5, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_5(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_7(macro, sep, data, seq) MA_IMPL_CALL(macro, 6, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_6(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_8(macro, sep, data, seq) MA_IMPL_CALL(macro, 7, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_7(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_9(macro, sep, data, seq) MA_IMPL_CALL(macro, 8, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_8(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_10(macro, sep, data, seq) MA_IMPL_CALL(macro, 9, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_9(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_11(macro, sep, data, seq) MA_IMPL_CALL(macro, 10, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_10(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_12(macro, sep, data, seq) MA_IMPL_CALL(macro, 11, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_11(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_13(macro, sep, data, seq) MA_IMPL_CALL(macro, 12, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_12(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_14(macro, sep, data, seq) MA_IMPL_CALL(macro, 13, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_13(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_15(macro, sep, data, seq) MA_IMPL_CALL(macro, 14, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_14(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_16(macro, sep, data, seq) MA_IMPL_CALL(macro, 15, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_15(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_17(macro, sep, data, seq) MA_IMPL_CALL(macro, 16, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_16(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_18(macro, sep, data, seq) MA_IMPL_CALL(macro, 17, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_17(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_19(macro, sep, data, seq) MA_IMPL_CALL(macro, 18, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_18(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_20(macro, sep, data, seq) MA_IMPL_CALL(macro, 19, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_19(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_21(macro, sep, data, seq) MA_IMPL_CALL(macro, 20, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_20(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_22(macro, sep, data, seq) MA_IMPL_CALL(macro, 21, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_21(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_23(macro, sep, data, seq) MA_IMPL_CALL(macro, 22, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_22(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_24(macro, sep, data, seq) MA_IMPL_CALL(macro, 23, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_23(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_25(macro, sep, data, seq) MA_IMPL_CALL(macro, 24, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_24(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_26(macro, sep, data, seq) MA_IMPL_CALL(macro, 25, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_25(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_27(macro, sep, data, seq) MA_IMPL_CALL(macro, 26, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_26(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_28(macro, sep, data, seq) MA_IMPL_CALL(macro, 27, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_27(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_29(macro, sep, data, seq) MA_IMPL_CALL(macro, 28, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_28(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_30(macro, sep, data, seq) MA_IMPL_CALL(macro, 29, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_29(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_31(macro, sep, data, seq) MA_IMPL_CALL(macro, 30, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_30(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_32(macro, sep, data, seq) MA_IMPL_CALL(macro, 31, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_31(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_33(macro, sep, data, seq) MA_IMPL_CALL(macro, 32, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_32(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_34(macro, sep, data, seq) MA_IMPL_CALL(macro, 33, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_33(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_35(macro, sep, data, seq) MA_IMPL_CALL(macro, 34, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_34(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_36(macro, sep, data, seq) MA_IMPL_CALL(macro, 35, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_35(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_37(macro, sep, data, seq) MA_IMPL_CALL(macro, 36, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_36(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_38(macro, sep, data, seq) MA_IMPL_CALL(macro, 37, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_37(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_39(macro, sep, data, seq) MA_IMPL_CALL(macro, 38, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_38(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_40(macro, sep, data, seq) MA_IMPL_CALL(macro, 39, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_39(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_41(macro, sep, data, seq) MA_IMPL_CALL(macro, 40, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_40(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_42(macro, sep, data, seq) MA_IMPL_CALL(macro, 41, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_41(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_43(macro, sep, data, seq) MA_IMPL_CALL(macro, 42, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_42(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_44(macro, sep, data, seq) MA_IMPL_CALL(macro, 43, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_43(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_45(macro, sep, data, seq) MA_IMPL_CALL(macro, 44, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_44(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_46(macro, sep, data, seq) MA_IMPL_CALL(macro, 45, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_45(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_47(macro, sep, data, seq) MA_IMPL_CALL(macro, 46, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_46(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_48(macro, sep, data, seq) MA_IMPL_CALL(macro, 47, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_47(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_49(macro, sep, data, seq) MA_IMPL_CALL(macro, 48, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_48(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_50(macro, sep, data, seq) MA_IMPL_CALL(macro, 49, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_49(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_51(macro, sep, data, seq) MA_IMPL_CALL(macro, 50, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_50(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_52(macro, sep, data, seq) MA_IMPL_CALL(macro, 51, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_51(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_53(macro, sep, data, seq) MA_IMPL_CALL(macro, 52, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_52(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_54(macro, sep, data, seq) MA_IMPL_CALL(macro, 53, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_53(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_55(macro, sep, data, seq) MA_IMPL_CALL(macro, 54, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_54(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_56(macro, sep, data, seq) MA_IMPL_CALL(macro, 55, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_55(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_57(macro, sep, data, seq) MA_IMPL_CALL(macro, 56, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_56(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_58(macro, sep, data, seq) MA_IMPL_CALL(macro, 57, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_57(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_59(macro, sep, data, seq) MA_IMPL_CALL(macro, 58, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_58(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_60(macro, sep, data, seq) MA_IMPL_CALL(macro, 59, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_59(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_61(macro, sep, data, seq) MA_IMPL_CALL(macro, 60, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_60(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_62(macro, sep, data, seq) MA_IMPL_CALL(macro, 61, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_61(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_63(macro, sep, data, seq) MA_IMPL_CALL(macro, 62, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_62(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_impl_64(macro, sep, data, seq) MA_IMPL_CALL(macro, 63, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_impl_63(macro, sep, data, MA_SEQ_NO_FIRST(seq))

#define MA_SEQ_FOR_EACH_A(macro, sep, data, seq) MA_CAT(MA_SEQ_FOR_EACH_A_impl_, MA_SEQ_SIZE(seq))(macro, sep, data, seq)
#define MA_SEQ_FOR_EACH_A_impl_0(macro, sep, data, seq)
#define MA_SEQ_FOR_EACH_A_impl_1(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 0, data, MA_SEQ_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_2(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 1, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_1(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_3(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 2, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_2(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_4(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 3, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_3(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_5(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 4, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_4(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_6(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 5, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_5(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_7(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 6, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_6(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_8(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 7, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_7(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_9(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 8, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_8(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_10(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 9, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_9(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_11(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 10, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_10(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_12(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 11, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_11(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_13(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 12, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_12(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_14(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 13, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_13(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_15(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 14, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_14(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_16(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 15, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_15(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_17(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 16, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_16(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_18(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 17, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_17(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_19(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 18, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_18(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_20(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 19, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_19(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_21(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 20, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_20(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_22(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 21, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_21(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_23(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 22, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_22(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_24(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 23, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_23(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_25(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 24, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_24(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_26(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 25, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_25(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_27(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 26, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_26(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_28(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 27, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_27(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_29(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 28, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_28(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_30(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 29, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_29(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_31(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 30, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_30(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_32(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 31, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_31(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_33(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 32, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_32(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_34(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 33, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_33(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_35(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 34, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_34(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_36(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 35, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_35(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_37(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 36, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_36(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_38(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 37, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_37(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_39(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 38, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_38(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_40(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 39, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_39(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_41(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 40, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_40(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_42(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 41, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_41(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_43(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 42, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_42(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_44(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 43, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_43(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_45(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 44, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_44(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_46(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 45, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_45(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_47(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 46, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_46(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_48(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 47, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_47(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_49(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 48, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_48(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_50(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 49, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_49(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_51(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 50, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_50(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_52(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 51, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_51(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_53(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 52, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_52(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_54(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 53, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_53(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_55(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 54, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_54(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_56(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 55, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_55(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_57(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 56, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_56(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_58(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 57, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_57(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_59(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 58, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_58(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_60(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 59, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_59(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_61(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 60, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_60(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_62(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 61, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_61(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_63(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 62, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_62(macro, sep, data, MA_SEQ_NO_FIRST(seq))
#define MA_SEQ_FOR_EACH_A_impl_64(macro, sep, data, seq) MA_IMPL_CALL_A(macro, 63, data, MA_SEQ_FIRST(seq)) sep() MA_SEQ_FOR_EACH_A_impl_63(macro, sep, data, MA_SEQ_NO_FIRST(seq))
