#pragma once

// This file is a part of CGLFL (configurable OpenGL function loader).
// Generated, do no edit!
//
// Version: 1.0.0
// API: gl 2.1
// Extensions: none

#define CGLFL_PRIMARY_FUNC_COUNT 551
#define CGLFL_PRIMARY_FUNCS \
    glAccum \
    glActiveTexture \
    glAlphaFunc \
    glAreTexturesResident \
    glArrayElement \
    glAttachShader \
    glBegin \
    glBeginQuery \
    glBindAttribLocation \
    glBindBuffer \
    glBindTexture \
    glBitmap \
    glBlendColor \
    glBlendEquation \
    glBlendEquationSeparate \
    glBlendFunc \
    glBlendFuncSeparate \
    glBufferData \
    glBufferSubData \
    glCallList \
    glCallLists \
    glClear \
    glClearAccum \
    glClearColor \
    glClearDepth \
    glClearIndex \
    glClearStencil \
    glClientActiveTexture \
    glClipPlane \
    glColor3b \
    glColor3bv \
    glColor3d \
    glColor3dv \
    glColor3f \
    glColor3fv \
    glColor3i \
    glColor3iv \
    glColor3s \
    glColor3sv \
    glColor3ub \
    glColor3ubv \
    glColor3ui \
    glColor3uiv \
    glColor3us \
    glColor3usv \
    glColor4b \
    glColor4bv \
    glColor4d \
    glColor4dv \
    glColor4f \
    glColor4fv \
    glColor4i \
    glColor4iv \
    glColor4s \
    glColor4sv \
    glColor4ub \
    glColor4ubv \
    glColor4ui \
    glColor4uiv \
    glColor4us \
    glColor4usv \
    glColorMask \
    glColorMaterial \
    glColorPointer \
    glCompileShader \
    glCompressedTexImage1D \
    glCompressedTexImage2D \
    glCompressedTexImage3D \
    glCompressedTexSubImage1D \
    glCompressedTexSubImage2D \
    glCompressedTexSubImage3D \
    glCopyPixels \
    glCopyTexImage1D \
    glCopyTexImage2D \
    glCopyTexSubImage1D \
    glCopyTexSubImage2D \
    glCopyTexSubImage3D \
    glCreateProgram \
    glCreateShader \
    glCullFace \
    glDeleteBuffers \
    glDeleteLists \
    glDeleteProgram \
    glDeleteQueries \
    glDeleteShader \
    glDeleteTextures \
    glDepthFunc \
    glDepthMask \
    glDepthRange \
    glDetachShader \
    glDisable \
    glDisableClientState \
    glDisableVertexAttribArray \
    glDrawArrays \
    glDrawBuffer \
    glDrawBuffers \
    glDrawElements \
    glDrawPixels \
    glDrawRangeElements \
    glEdgeFlag \
    glEdgeFlagPointer \
    glEdgeFlagv \
    glEnable \
    glEnableClientState \
    glEnableVertexAttribArray \
    glEnd \
    glEndList \
    glEndQuery \
    glEvalCoord1d \
    glEvalCoord1dv \
    glEvalCoord1f \
    glEvalCoord1fv \
    glEvalCoord2d \
    glEvalCoord2dv \
    glEvalCoord2f \
    glEvalCoord2fv \
    glEvalMesh1 \
    glEvalMesh2 \
    glEvalPoint1 \
    glEvalPoint2 \
    glFeedbackBuffer \
    glFinish \
    glFlush \
    glFogCoordPointer \
    glFogCoordd \
    glFogCoorddv \
    glFogCoordf \
    glFogCoordfv \
    glFogf \
    glFogfv \
    glFogi \
    glFogiv \
    glFrontFace \
    glFrustum \
    glGenBuffers \
    glGenLists \
    glGenQueries \
    glGenTextures \
    glGetActiveAttrib \
    glGetActiveUniform \
    glGetAttachedShaders \
    glGetAttribLocation \
    glGetBooleanv \
    glGetBufferParameteriv \
    glGetBufferPointerv \
    glGetBufferSubData \
    glGetClipPlane \
    glGetCompressedTexImage \
    glGetDoublev \
    glGetError \
    glGetFloatv \
    glGetIntegerv \
    glGetLightfv \
    glGetLightiv \
    glGetMapdv \
    glGetMapfv \
    glGetMapiv \
    glGetMaterialfv \
    glGetMaterialiv \
    glGetPixelMapfv \
    glGetPixelMapuiv \
    glGetPixelMapusv \
    glGetPointerv \
    glGetPolygonStipple \
    glGetProgramInfoLog \
    glGetProgramiv \
    glGetQueryObjectiv \
    glGetQueryObjectuiv \
    glGetQueryiv \
    glGetShaderInfoLog \
    glGetShaderSource \
    glGetShaderiv \
    glGetString \
    glGetTexEnvfv \
    glGetTexEnviv \
    glGetTexGendv \
    glGetTexGenfv \
    glGetTexGeniv \
    glGetTexImage \
    glGetTexLevelParameterfv \
    glGetTexLevelParameteriv \
    glGetTexParameterfv \
    glGetTexParameteriv \
    glGetUniformLocation \
    glGetUniformfv \
    glGetUniformiv \
    glGetVertexAttribPointerv \
    glGetVertexAttribdv \
    glGetVertexAttribfv \
    glGetVertexAttribiv \
    glHint \
    glIndexMask \
    glIndexPointer \
    glIndexd \
    glIndexdv \
    glIndexf \
    glIndexfv \
    glIndexi \
    glIndexiv \
    glIndexs \
    glIndexsv \
    glIndexub \
    glIndexubv \
    glInitNames \
    glInterleavedArrays \
    glIsBuffer \
    glIsEnabled \
    glIsList \
    glIsProgram \
    glIsQuery \
    glIsShader \
    glIsTexture \
    glLightModelf \
    glLightModelfv \
    glLightModeli \
    glLightModeliv \
    glLightf \
    glLightfv \
    glLighti \
    glLightiv \
    glLineStipple \
    glLineWidth \
    glLinkProgram \
    glListBase \
    glLoadIdentity \
    glLoadMatrixd \
    glLoadMatrixf \
    glLoadName \
    glLoadTransposeMatrixd \
    glLoadTransposeMatrixf \
    glLogicOp \
    glMap1d \
    glMap1f \
    glMap2d \
    glMap2f \
    glMapBuffer \
    glMapGrid1d \
    glMapGrid1f \
    glMapGrid2d \
    glMapGrid2f \
    glMaterialf \
    glMaterialfv \
    glMateriali \
    glMaterialiv \
    glMatrixMode \
    glMultMatrixd \
    glMultMatrixf \
    glMultTransposeMatrixd \
    glMultTransposeMatrixf \
    glMultiDrawArrays \
    glMultiDrawElements \
    glMultiTexCoord1d \
    glMultiTexCoord1dv \
    glMultiTexCoord1f \
    glMultiTexCoord1fv \
    glMultiTexCoord1i \
    glMultiTexCoord1iv \
    glMultiTexCoord1s \
    glMultiTexCoord1sv \
    glMultiTexCoord2d \
    glMultiTexCoord2dv \
    glMultiTexCoord2f \
    glMultiTexCoord2fv \
    glMultiTexCoord2i \
    glMultiTexCoord2iv \
    glMultiTexCoord2s \
    glMultiTexCoord2sv \
    glMultiTexCoord3d \
    glMultiTexCoord3dv \
    glMultiTexCoord3f \
    glMultiTexCoord3fv \
    glMultiTexCoord3i \
    glMultiTexCoord3iv \
    glMultiTexCoord3s \
    glMultiTexCoord3sv \
    glMultiTexCoord4d \
    glMultiTexCoord4dv \
    glMultiTexCoord4f \
    glMultiTexCoord4fv \
    glMultiTexCoord4i \
    glMultiTexCoord4iv \
    glMultiTexCoord4s \
    glMultiTexCoord4sv \
    glNewList \
    glNormal3b \
    glNormal3bv \
    glNormal3d \
    glNormal3dv \
    glNormal3f \
    glNormal3fv \
    glNormal3i \
    glNormal3iv \
    glNormal3s \
    glNormal3sv \
    glNormalPointer \
    glOrtho \
    glPassThrough \
    glPixelMapfv \
    glPixelMapuiv \
    glPixelMapusv \
    glPixelStoref \
    glPixelStorei \
    glPixelTransferf \
    glPixelTransferi \
    glPixelZoom \
    glPointParameterf \
    glPointParameterfv \
    glPointParameteri \
    glPointParameteriv \
    glPointSize \
    glPolygonMode \
    glPolygonOffset \
    glPolygonStipple \
    glPopAttrib \
    glPopClientAttrib \
    glPopMatrix \
    glPopName \
    glPrioritizeTextures \
    glPushAttrib \
    glPushClientAttrib \
    glPushMatrix \
    glPushName \
    glRasterPos2d \
    glRasterPos2dv \
    glRasterPos2f \
    glRasterPos2fv \
    glRasterPos2i \
    glRasterPos2iv \
    glRasterPos2s \
    glRasterPos2sv \
    glRasterPos3d \
    glRasterPos3dv \
    glRasterPos3f \
    glRasterPos3fv \
    glRasterPos3i \
    glRasterPos3iv \
    glRasterPos3s \
    glRasterPos3sv \
    glRasterPos4d \
    glRasterPos4dv \
    glRasterPos4f \
    glRasterPos4fv \
    glRasterPos4i \
    glRasterPos4iv \
    glRasterPos4s \
    glRasterPos4sv \
    glReadBuffer \
    glReadPixels \
    glRectd \
    glRectdv \
    glRectf \
    glRectfv \
    glRecti \
    glRectiv \
    glRects \
    glRectsv \
    glRenderMode \
    glRotated \
    glRotatef \
    glSampleCoverage \
    glScaled \
    glScalef \
    glScissor \
    glSecondaryColor3b \
    glSecondaryColor3bv \
    glSecondaryColor3d \
    glSecondaryColor3dv \
    glSecondaryColor3f \
    glSecondaryColor3fv \
    glSecondaryColor3i \
    glSecondaryColor3iv \
    glSecondaryColor3s \
    glSecondaryColor3sv \
    glSecondaryColor3ub \
    glSecondaryColor3ubv \
    glSecondaryColor3ui \
    glSecondaryColor3uiv \
    glSecondaryColor3us \
    glSecondaryColor3usv \
    glSecondaryColorPointer \
    glSelectBuffer \
    glShadeModel \
    glShaderSource \
    glStencilFunc \
    glStencilFuncSeparate \
    glStencilMask \
    glStencilMaskSeparate \
    glStencilOp \
    glStencilOpSeparate \
    glTexCoord1d \
    glTexCoord1dv \
    glTexCoord1f \
    glTexCoord1fv \
    glTexCoord1i \
    glTexCoord1iv \
    glTexCoord1s \
    glTexCoord1sv \
    glTexCoord2d \
    glTexCoord2dv \
    glTexCoord2f \
    glTexCoord2fv \
    glTexCoord2i \
    glTexCoord2iv \
    glTexCoord2s \
    glTexCoord2sv \
    glTexCoord3d \
    glTexCoord3dv \
    glTexCoord3f \
    glTexCoord3fv \
    glTexCoord3i \
    glTexCoord3iv \
    glTexCoord3s \
    glTexCoord3sv \
    glTexCoord4d \
    glTexCoord4dv \
    glTexCoord4f \
    glTexCoord4fv \
    glTexCoord4i \
    glTexCoord4iv \
    glTexCoord4s \
    glTexCoord4sv \
    glTexCoordPointer \
    glTexEnvf \
    glTexEnvfv \
    glTexEnvi \
    glTexEnviv \
    glTexGend \
    glTexGendv \
    glTexGenf \
    glTexGenfv \
    glTexGeni \
    glTexGeniv \
    glTexImage1D \
    glTexImage2D \
    glTexImage3D \
    glTexParameterf \
    glTexParameterfv \
    glTexParameteri \
    glTexParameteriv \
    glTexSubImage1D \
    glTexSubImage2D \
    glTexSubImage3D \
    glTranslated \
    glTranslatef \
    glUniform1f \
    glUniform1fv \
    glUniform1i \
    glUniform1iv \
    glUniform2f \
    glUniform2fv \
    glUniform2i \
    glUniform2iv \
    glUniform3f \
    glUniform3fv \
    glUniform3i \
    glUniform3iv \
    glUniform4f \
    glUniform4fv \
    glUniform4i \
    glUniform4iv \
    glUniformMatrix2fv \
    glUniformMatrix2x3fv \
    glUniformMatrix2x4fv \
    glUniformMatrix3fv \
    glUniformMatrix3x2fv \
    glUniformMatrix3x4fv \
    glUniformMatrix4fv \
    glUniformMatrix4x2fv \
    glUniformMatrix4x3fv \
    glUnmapBuffer \
    glUseProgram \
    glValidateProgram \
    glVertex2d \
    glVertex2dv \
    glVertex2f \
    glVertex2fv \
    glVertex2i \
    glVertex2iv \
    glVertex2s \
    glVertex2sv \
    glVertex3d \
    glVertex3dv \
    glVertex3f \
    glVertex3fv \
    glVertex3i \
    glVertex3iv \
    glVertex3s \
    glVertex3sv \
    glVertex4d \
    glVertex4dv \
    glVertex4f \
    glVertex4fv \
    glVertex4i \
    glVertex4iv \
    glVertex4s \
    glVertex4sv \
    glVertexAttrib1d \
    glVertexAttrib1dv \
    glVertexAttrib1f \
    glVertexAttrib1fv \
    glVertexAttrib1s \
    glVertexAttrib1sv \
    glVertexAttrib2d \
    glVertexAttrib2dv \
    glVertexAttrib2f \
    glVertexAttrib2fv \
    glVertexAttrib2s \
    glVertexAttrib2sv \
    glVertexAttrib3d \
    glVertexAttrib3dv \
    glVertexAttrib3f \
    glVertexAttrib3fv \
    glVertexAttrib3s \
    glVertexAttrib3sv \
    glVertexAttrib4Nbv \
    glVertexAttrib4Niv \
    glVertexAttrib4Nsv \
    glVertexAttrib4Nub \
    glVertexAttrib4Nubv \
    glVertexAttrib4Nuiv \
    glVertexAttrib4Nusv \
    glVertexAttrib4bv \
    glVertexAttrib4d \
    glVertexAttrib4dv \
    glVertexAttrib4f \
    glVertexAttrib4fv \
    glVertexAttrib4iv \
    glVertexAttrib4s \
    glVertexAttrib4sv \
    glVertexAttrib4ubv \
    glVertexAttrib4uiv \
    glVertexAttrib4usv \
    glVertexAttribPointer \
    glVertexPointer \
    glViewport \
    glWindowPos2d \
    glWindowPos2dv \
    glWindowPos2f \
    glWindowPos2fv \
    glWindowPos2i \
    glWindowPos2iv \
    glWindowPos2s \
    glWindowPos2sv \
    glWindowPos3d \
    glWindowPos3dv \
    glWindowPos3f \
    glWindowPos3fv \
    glWindowPos3i \
    glWindowPos3iv \
    glWindowPos3s \
    glWindowPos3sv

#define CGLFL_EXT_COUNT 0
#define CGLFL_EXTS(X) // None
